const bcrypt = require("bcryptjs");

const data = {
  users: [
    {
      firstName: "ameer",
      lastName: "emran",
      city: "Maghar",
      address: "Maghar",
      idNumber: "201259595",
      email: "ameer.em.89@gmail.com",
      password: bcrypt.hashSync("VM682PHE"),
      isAdmin: true,
      cart: [],
    },
    {
      firstName: "user",
      lastName: "user",
      city: "tel aviv",
      address: "tel aviv",
      idNumber: "123456789",
      email: "user1@user.com",
      password: bcrypt.hashSync("user1"),
      isAdmin: false,
      cart: [],
    },
  ],
  products: [
    {
      name: "Ananas",
      category: "Vegetables & Fruits",
      image: "ananas.jpg", // 679px x 829x
      price: 50,
      countInStock: 20,
      rating: 4.5,
      numReviews: 10,
      description: "delecious fruits",
    },

    {
      name: "Bamba",
      category: "Candys",
      image: "bamba.jpg",
      price: 5,
      countInStock: 40,
      rating: 3,
      numReviews: 8,
      description: "good bamba",
    },
    {
      name: "bambabesli",
      category: "Candys",
      image: "bambabesli.jpg",
      price: 8,
      countInStock: 100,
      rating: 2.5,
      numReviews: 6,
      description: "good bambabesli",
    },
    {
      name: "banana",
      category: "Vegetables & Fruits",
      image: "banana.jpg",
      price: 10,
      countInStock: 12,
      rating: 2.5,
      numReviews: 6,
      description: "high quality banana",
    },
    {
      name: "beer",
      category: "Drinks",
      image: "beer.jpg",
      price: 90,
      countInStock: 12,
      rating: 2.5,
      numReviews: 6,
      description: "high quality Beer",
    },
    {
      name: "bread",
      category: "Bread/Bakery",
      image: "bread.jpg",
      price: 15,
      countInStock: 30,
      rating: 2.5,
      numReviews: 6,
      description: "delecious bread",
    },
    {
      name: "buns",
      category: "Bread/Bakery",
      image: "buns.jpg",
      price: 20,
      countInStock: 12,
      rating: 2.5,
      numReviews: 6,
      description: "delecious buns",
    },
    {
      name: "chicken",
      category: "Meat & Fish",
      image: "chicken.jpg",
      price: 25,
      countInStock: 70,
      rating: 2.5,
      numReviews: 6,
      description: "high quality chicken",
    },
    {
      name: "cocacola",
      category: "Drinks",
      image: "cocacola.jpg",
      price: 10,
      countInStock: 12,
      rating: 2.5,
      numReviews: 6,
      description: "good and delecios drink",
    },
    {
      name: "cucambers",
      category: "Vegetables & Fruits",
      image: "cucambers.jpg",
      price: 50,
      countInStock: 12,
      rating: 2.5,
      numReviews: 6,
      description: "good quality cucambers",
    },
    {
      name: "eggs",
      category: "Milk & Eggs",
      image: "eggs.jpg",
      price: 30,
      countInStock: 40,
      rating: 2.5,
      numReviews: 6,
      description: "eggs with high quality",
    },
    {
      name: "koteg",
      category: "Milk & Eggs",
      image: "koteg.png",
      price: 12,
      countInStock: 60,
      rating: 2.5,
      numReviews: 6,
      description: "deldecious koteg",
    },
    {
      name: "Loaker",
      category: "Candys",
      image: "luaker.png",
      price: 18,
      countInStock: 35,
      rating: 2.5,
      numReviews: 6,
      description: "high quality chocolate",
    },
    {
      name: "meat",
      category: "Meat & Fish",
      image: "meat.jpg",
      price: 90,
      countInStock: 50,
      rating: 2.5,
      numReviews: 6,
      description: "high quality meat",
    },
    {
      name: "milk",
      category: "Milk & Eggs",
      image: "milk.jpg",
      price: 90,
      countInStock: 25,
      rating: 2.5,
      numReviews: 6,
      description: "high quality milk",
    },
    {
      name: "nutella",
      category: "Candys",
      image: "nutella-jar.jpg",
      price: 90,
      countInStock: 25,
      rating: 2.5,
      numReviews: 6,
      description: "delecious chocolate",
    },
    {
      name: "oreo",
      category: "Candys",
      image: "oreo.jpg",
      price: 90,
      countInStock: 12,
      rating: 2.5,
      numReviews: 6,
      description: "delecious bescuit",
    },
    {
      name: "Potato",
      category: "Vegetables & Fruits",
      image: "Potato.jpg",
      price: 90,
      countInStock: 60,
      rating: 2.5,
      numReviews: 6,
      description: "high quality Potato",
    },
    {
      name: "sano",
      category: "Cleaners",
      image: "sano.jpg",
      price: 90,
      countInStock: 35,
      rating: 2.5,
      numReviews: 6,
      description: "high quality Cleaner",
    },
    {
      name: "shoko",
      category: "Milk & Eggs",
      image: "shoko.jpg",
      price: 90,
      countInStock: 23,
      rating: 2.5,
      numReviews: 6,
      description: "delecious drink",
    },
    {
      name: "strawberry",
      category: "Vegetables & Fruits",
      image: "strawberry.jpg",
      price: 90,
      countInStock: 15,
      rating: 2.5,
      numReviews: 6,
      description: "high quality and good strawberry",
    },
  ],
};

module.exports = data;
